name: PSALM (php-actions)
description: |
  PHP Static Analysis in Github Actions.

  This action needs origin/master to be available by checkout and composer install.

  ```yaml
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name : Install dependencies
      uses : php-actions/composer@v6

    - name : Psalm
      uses : kronostechnologies/actions/psalm@v0.0.8
  ```

  If fetch-depth is not set or greater than 0 you can add a step to fetch the origin/master branch

  ```yaml
  - name : Fetch origin/master
    run : |
      git fetch --no-tags --prune --depth=1000 origin +refs/heads/master:refs/remotes/origin/master
  ```

inputs:
  php_version:
    description: What version of PHP to use
    default: latest
    required: false

  php_extensions:
    description: Space separated list of extensions to configure with the PHP build
    required: false

  memory_limit:
    description: Memory limit for analysis
    required: false

  args:
    description: Extra arguments to pass to the psalm binary
    required: false

  only_changed_files:
    description : "Run psalm analysis only on changed files compared to master. Or previous commit for master branch."
    required : false
    default : false

runs:
  using: "composite"
  steps:
    - env:
        ACTION_TOKEN: ${{ github.token }}
        ACTION_PHP_VERSION: ${{ inputs.php_version }}
        ACTION_PHP_EXTENSIONS: ${{ inputs.php_extensions }}
        ACTION_LEVEL: ${{ inputs.level }}
        ACTION_MEMORY_LIMIT: ${{ inputs.memory_limit }}
        ACTION_ARGS: ${{ inputs.args }}
        ACTION_ONLY_CHANGED_FILES: ${{ inputs.only_changed_files }}
      id: psalm_run
      run: bash <(curl -s https://raw.githubusercontent.com/php-actions/php-build/330b13bbb1eadd05bbb627477c1549cd7e62e406/php-build.bash) psalm \
        && ${{ github.action_path }}/psalm-action.bash || { echo "::group::Debug output" ; cat ${{ github.workspace }}/output.log ; echo "::endgroup::" ; exit 1; }
      shell: bash

branding:
  icon: 'check-square'
  color: 'purple'
