name: Resolve common application metadata
description: |
  Resolve common application metadata like the application version or whether it is publishable (by our standards).

  Git "history" must be available for this action to perform well. A typical usage will look like so:

  ```yaml
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Find latest released version
      id: latest
      uses: oprypin/find-latest-tag@v1
      continue-on-error: true
      with:
        repository: $ {{ github.repository }}
        releases-only: false
        prefix: v
        regex: '^v\d+\.\d+\.\d+$'
        sort-tags: true

    - name: Find application metadata
      id: metadata
      uses: .github/actions/application-metadata
      with:
        latest-release-tag: $ {{ steps.latest.outputs.tag }}
  ```

inputs:
  latest-release-tag:
    description: The tag pointing to the latest released version.
    required: false

outputs:
  publishable:
    description: |
      'true' if this build can publish artifacts. Only builds from the default branch can be published.
      'false' if this build should not publish its artifacts.
    value: ${{ steps.metadata.outputs.publishable }}
  is-release:
    description: |
      'true' if this build should create a full release. Only 'publishable' builds can be released. A release is
        typically triggered from a tag matching the 'v1.2.3', semver format.
      'false' if this build should not create a full release.
    value: ${{ steps.metadata.outputs.is_release }}
  version:
    description: |
      The resolved version that the current build can use.
      The version will usually be semver compliant only for releases.
    value: ${{ steps.metadata.outputs.version }}

runs:
  using: composite
  steps:
    - name: Find application metadata
      id: metadata
      shell: bash
      run: |
        PUBLISHABLE=false
        IS_RELEASE=false
        VERSION=0.0.0-SNAPSHOT
        DEFAULT_BRANCH=${{ github.event.repository.default_branch }}

        LATEST_VERSION=${{ inputs.latest-release-tag }}
        LATEST_VERSION=${LATEST_VERSION#v}
        LATEST_VERSION=${LATEST_VERSION:-0.0.0}

        if [[ "$DEFAULT_BRANCH" == "" ]]; then
          # Schedule triggers have no `github.event` contexts
          DEFAULT_BRANCH="${GITHUB_REF#refs/heads/}"
        fi

        if [[ $GITHUB_REF =~ refs/tags/v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
          PUBLISHABLE=$(git merge-base --is-ancestor "$GITHUB_SHA" "origin/$DEFAULT_BRANCH" && echo "true" || echo "false")
          IS_RELEASE="$PUBLISHABLE"
        elif [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=$(echo ${GITHUB_REF#refs/tags/} | sed -r 's#/+#-#g')
        elif [[ $GITHUB_REF == refs/heads/* ]]; then
          BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
          if [ "$DEFAULT_BRANCH" = "$BRANCH" ]; then
            VERSION=${LATEST_VERSION%.*}.$((${LATEST_VERSION##*.} + 1))-SNAPSHOT
            PUBLISHABLE=true
          else
            VERSION=branch-$BRANCH
          fi
        elif [[ $GITHUB_REF == refs/pull/* ]]; then
          VERSION=pr-${{ github.event.number }}
        fi

        echo ::set-output name=is-release::$IS_RELEASE
        echo ::set-output name=publishable::$PUBLISHABLE
        echo ::set-output name=version::$VERSION
